# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "drksci-studio"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[env]
  PORT = "8080"
  NODE_ENV = "production"

# Secrets to be set via: fly secrets set KEY=VALUE
# - ANTHROPIC_API_KEY
# - OPENAI_API_KEY (optional)
# - GOOGLE_API_KEY (optional)

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
